#!/usr/bin/env bash
# Displays information about the file `school file`.

if [ -e "school file" ]
then
  echo "school file exists"
  if [ -s "school file" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi

  if [ -f "school file" ]
  then
    echo "school file is a regular file"
  fi
else
  echo "school file does not exist"
fi
